{% set version = "5.7.2" %}
{% set commit = "e12caae2b363bf2f80f418e3cebbcc25442a3bfe" %}
{% set siriusDistDir = "sirius_gui_dist" %}

package:
  name: sirius-ms
  version: {{ version }}

source:
  - url: https://github.com/boecker-lab/sirius/archive/{{ commit }}.zip
    sha256: 09548db1ad10dbea0bc17c220b1f86cccfbd696f49ca52e74b7ec93788e99f52

build:
  number: 0
  script_env:
    - siriusDistName={{ siriusDistDir }}-sirius
    - siriusDistDir={{ siriusDistDir }}

requirements:
  build:
    - openjdk
  run:
    - openjdk
    - coin-or-cbc  # [not win]

test:
  requires:
    - wget  # [not win]

about:
  home: https://bio.informatik.uni-jena.de/software/sirius/
  license: AGPL-3.0-only AND OTHER
  license_file:
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/COPYING.txt
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/LICENSE.txt
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/licenses.md
  summary: "SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS"
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other
    small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID
    (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command line version
    of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
