{% set version = "6.3.1" %}
{% set siriusDistDir = "sirius_gui_dist" %}

package:
  name: sirius-ms
  version: {{ version }}

source:
  - url: https://github.com/sirius-ms/sirius/archive/refs/tags/v{{ version }}-SNAPSHOT.zip
    sha256: 2f31db7f20fee98cb5304cf79abda929e688e6dda9282dd0b5d91252289384eb

build:
  skip: "{{ ('linux' in target_platform and 'aarch64' in target_platform) or ('ppc64le' in target_platform) }}"
  number: 0
  script_env:
    - siriusDistName={{ siriusDistDir }}-sirius
    - siriusDistDir={{ siriusDistDir }}

requirements:
  build:
    - openjdk 21.*
  run:
    - openjdk 21.*
    - coin-or-cbc 2.10.*

test:
  requires:
    - wget  # [not win]

about:
  home: https://github.com/sirius-ms/sirius
  license: AGPL-3.0-only AND OTHER
  license_file:
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/COPYING.txt
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/LICENSE.txt
    - sirius_dist/{{ siriusDistDir }}/build/install/{{ siriusDistDir }}-sirius/licenses.md
  summary: 'SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS'
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command
    line version of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://v6.docs.sirius-ms.io/
  dev_url: https://github.com/sirius-ms/sirius

extra:
  recipe-maintainers:
    - mfleisch
